{% set name = "pyram" %}
{% set version = "1.1.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c7c8fd426caa8060c4e435aa9f90b7104a014f765d1a085b2d8af38cc88857ce" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy >=1.14
    - numba >=0.37
  run:
    - python
    - numpy >=1.14
    - numba >=0.37

test:
  imports:
    - pyram
    - pyram.Tests

about:
  home: https://github.com/marcuskd/pyram
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Python adaptation of the Range-dependent Acoustic Model (RAM)
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
